---
version: '3'

services:
  create-pypkg:
    container_name: create-pypkg
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/create-pypkg:latest
    volumes:
      - .:/wd
    working_dir: /wd
    entrypoint:
      - create-pypkg
